### ISSUE TITLE
论文放到ａｒｘｉｖ了吗

### ISSUE THREAD

**Issue by Alexadlu** [zhang-pengyu/ADRNet#1]
这个是基于Siamese框架还是RT-MDNet框架呀

**Comment by zhang-pengyu** [comment]
是基于RTMDNet的，论文我再检查一遍然后会放到arxiv上，感谢关注～

**Comment by zhang-pengyu** [comment]
https://github.com/zhang-pengyu/ADRNet/blob/main/Zhang_IJCV2021_ADRNet.pdf
论文我上传到github上了，可以点击链接查看

**Comment by Alexadlu** [comment]
好的 IJCV大佬
