### ISSUE TITLE
关于多步训练

### ISSUE THREAD

**Issue by caiyujue** [zhang-pengyu/ADRNet#11]
我想请问下,在论文里的分步训练的第二步训练AENet时,论文里说要冻结主干.ADRB和FC,这里的FC层,是FC4.FC5.FC6吗,包不包括FC6啊,还有就是怎么最小化公式6的那个权重Ma,这边没怎么看明白,希望作者大大能看到,回复一下

**Comment by zhang-pengyu** [comment]
你好，不需要冻结FC6，另外第二步也是优化第一步里（eq.8）来得到权重Ma
