### ISSUE TITLE
数据集下载

### ISSUE THREAD

**Issue by bxkzcb** [zhang-pengyu/ADRNet#7]
您好，能不能给个代码相关数据集的下载链接？

**Comment by zhang-pengyu** [comment]
您好，GTOT，RGBT234， VOT19-RGBT数据集下载可见 https://github.com/zhang-pengyu/Multimodal-Tracking-Survey#dataset
attribute-specific 数据可使用 data_generation文件夹中的代码获取

**Comment by bxkzcb** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    收到，万分感谢
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1106107028
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年9月16日 17:32，Pengyu ***@***.***> 写道： 




您好，GTOT，RGBT234， VOT19-RGBT数据集下载可见 https://github.com/zhang-pengyu/Multimodal-Tracking-Survey#dataset

attribute-specific 数据可使用 data_generation文件夹中的代码获取



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
