### ISSUE TITLE
RuntimeError: Error building extension '_prroi_pooling'

### ISSUE THREAD

**Issue by DZSYUNNAN** [zhang-pengyu/ADRNet#8]
when I run python Run_test.py, I have encountered this problem, could you give me some ideas to solve it

**Comment by easycodesniper-afk** [comment]
> The preciseROIPooling should be compiled following the instruction in the original repository (https://github.com/vacancy/PreciseRoIPooling).

I'm sorry but have you noticed that there is nothing about PreciseRoIPooling compile on **Pytorch** in the repo you provided?

**Comment by easycodesniper-afk** [comment]
Hi, have you solved your problem? I've met the same one.

**Comment by zhang-pengyu** [comment]
@easycodesniper-afk Hi~,the step-by-step setup is here. https://github.com/vacancy/PreciseRoIPooling#step-by-step-instructions

**Comment by easycodesniper-afk** [comment]
> @easycodesniper-afk Hi~,the step-by-step setup is here. https://github.com/vacancy/PreciseRoIPooling#step-by-step-instructions

thx but I don't use tensorflow.

**Comment by easycodesniper-afk** [comment]
> @easycodesniper-afk Hi~,the step-by-step setup is here. https://github.com/vacancy/PreciseRoIPooling#step-by-step-instructions

Hi, past days I tried kinds of ways, including updating my gcc/g++ vesion, and installing other version cuda & pytorch, but it doesn't work for this problem.My working environment is Ubuntu 16.04, gcc/g++6, cuda9.2, gtx 1080ti. Could you share your experience about compling preciseROIPooling?

**Comment by easycodesniper-afk** [comment]
Hi, I've solved this problem.I hope this blog would help you.https://blog.csdn.net/dongwanli666/article/details/104656679
